/**
 * ScriptGuard - background (event) page.
 *
 * The background page runs the NETWORK firewall. Script deletion itself
 * still happens in content.js, directly in the DOM.
 *
 * Responsibilities:
 *   1. Seed default settings on first install.
 *   2. Maintain a per-tab badge showing how many scripts were deleted.
 *   3. Reflect the active mode in the toolbar: icon colour
 *      (OFF=gray, BASIC=green, PRO=yellow, MAXIMUM=red), tooltip.
 *   4. Ad & tracker firewall: webRequest-level blocking of requests to
 *      known ad / tracker hosts (armed in PRO + MAXIMUM, or everywhere).
 *   5. Privacy headers: Sec-GPC + DNT on every request.
 *   6. Tracking-parameter stripping (utm_*, fbclid, gclid, ...) on nav.
 *   7. Optional auto-wipe: clear a site's data when its tab closes.
 *   8. Export / import the rule database (JSON) for backup and sharing.
 *
 * Everything here uses the promise-based `browser.*` namespace (Firefox).
 */

'use strict';

/* ---------------------------------------------------------------------
 * Default settings
 *
 * The shape of storage.local:
 *   {
 *     mode: "OFF" | "BASIC" | "PRO" | "MAXIMUM",
 *     rules:     { "<site>": ["<pattern>", ...], ... },
 *     whitelist: { "<site>": ["<pattern>", ...], ... },
 *     globalWhitelist: ["<pattern>", ...],
 *     regexRules:      ["<RegExp source>", ...],
 *     heuristics: { "<site>": ["<pattern>", ...], ... },
 *     shields:   { webrtc: true, blob: true },
 *     firewall:  { adBlockMode: "off"|"armed"|"always",
 *                  stripTracking: true, gpc: true, autoWipe: false },
 *     labels:    { "<site>": { "<pattern>": "<human label>" }, ... },
 *     trustedSites: ["<host>", ...],
 *     stats:     { "<site>": <deleted count> },
 *     netStats:  { "<site>": <requests blocked by the firewall> }
 *   }
 *
 * A pattern is either a normalized script URL, an "inline:<hash>" marker
 * for inline scripts, or a URL prefix ending in "*" (wildcard).
 *
 * BASIC is the factory default on purpose: a fresh install must never
 * silently break the web. Users opt into PRO / MAXIMUM themselves.
 * ------------------------------------------------------------------- */

const DEFAULTS = {
  mode: 'BASIC',
  rules: {},
  whitelist: {},
  globalWhitelist: [],
  regexRules: [],
  heuristics: {},
  shields: { webrtc: true, blob: true },
  firewall: {
    adBlockMode: 'armed',  // 'off' | 'armed' (BASIC + PRO + MAXIMUM; 'always' kept as legacy alias)
    stripTracking: true,   // remove utm_*/fbclid/gclid/... from URLs
    gpc: true,             // Sec-GPC + DNT headers
    autoWipe: false        // wipe site data when its tab closes
  },
  labels: {},
  trustedSites: [],
  stats: {},
  netStats: {}             // site -> requests blocked by the firewall
};

const ALL_KEYS = Object.keys(DEFAULTS);
const VALID_MODES = ['OFF', 'BASIC', 'PRO', 'MAXIMUM'];

/* ---------------------------------------------------------------------
 * Mode indicator: icon + badge colours.
 * OFF = gray, BASIC = green, PRO = yellow, MAXIMUM = red.
 * The tinted icon files are generated by scriptguard-tools/generate_icons.py
 * (outside the add-on package) and keep the shield design - only the badge
 * background changes colour.
 * ------------------------------------------------------------------- */

const MODE_ICONS = {
  OFF: 'off',
  BASIC: 'basic',
  PRO: 'pro',
  MAXIMUM: 'maximum'
};

const MODE_BADGE_COLORS = {
  OFF: '#6b7280',
  BASIC: '#22c55e',
  PRO: '#f59e0b',
  MAXIMUM: '#ef4444'
};

function iconPaths(mode) {
  const variant = MODE_ICONS[mode] || 'basic';
  return {
    16: 'icons/icon16-' + variant + '.png',
    32: 'icons/icon32-' + variant + '.png',
    48: 'icons/icon48-' + variant + '.png',
    96: 'icons/icon96-' + variant + '.png',
    128: 'icons/icon128-' + variant + '.png'
  };
}

/* ---------------------------------------------------------------------
 * 1b. Ad & tracker firewall database
 *
 * Deliberately readable: flat lists a human can audit. HOST suffix
 * matching catches every subdomain; PATH patterns only ever apply to
 * THIRD-party requests so a first-party path like /admin can never hit
 * the generic "ad" fragments.
 * ------------------------------------------------------------------- */

const AD_HOSTS = [
  // Google ads / DoubleClick
  'doubleclick.net', 'googlesyndication.com', 'googleadservices.com',
  'googletagservices.com', 'google-analytics.com', 'googletagmanager.com',
  'adservice.google.com', 'pagead2.googlesyndication.com', 'adclick.g.doubleclick.net',
  'googletagmanager.net', 'app-measurement.com',
  // Big ad exchanges / SSPs / DSPs
  'adnxs.com', 'adsafeprotected.com', 'adform.net', 'adroll.com',
  'adsrvr.org', 'rubiconproject.com', 'pubmatic.com', 'openx.net',
  'criteo.com', 'criteo.net', 'casalemedia.com', 'indexww.com',
  'sharethrough.com', 'smartadserver.com', 'adition.com', 'yieldmo.com',
  'bidswitch.net', 'districtm.io', 'media.net', 'system1.com',
  '33across.com', 'engagebdr.com', 'sonobi.com', 'gumgum.com',
  'undertone.com', 'synacor.com', 'conversantmedia.com', 'advertising.com',
  'tremorhub.com', 'spotxchange.com', 'spotx.tv', 'teads.tv',
  'springserve.com', 'theadex.com', 'improvedigital.com', 'liftmanagers.com',
  'openweb.com', 'triplelift.com', 'bidr.io', 'amazon-adsystem.com',
  // Native ads / content recommendation
  'taboola.com', 'outbrain.com', 'revcontent.com', 'mgid.com',
  'zergnet.com', 'content-ad.net', 'ad-maven.com', 'propellerads.com',
  'propellerclick.com', 'adcash.com', 'popads.net', 'popcash.net',
  'exoclick.com', 'exosrv.com', 'juicyads.com', 'trafficjunky.com',
  'trafficfactory.biz', 'hilltopads.net', 'clickaine.com', 'adtng.com',
  // Ad tech / verification / measurement
  'moatads.com', 'doubleverify.com', 'ads.yahoo.com', 'advertising.yahoo.com',
  'scorecardresearch.com', 'quantserve.com', 'quantcount.com', 'comscore.com',
  'sitescout.com', 'sizmek.com', 'flashtalking.com', 'innovid.com',
  'nimbus.adtechus.com', 'adtechus.com', 'adtech.de', 'imrworldwide.com',
  'hitwise.com', 'chartbeat.com', 'parsely.com', 'postrelease.com',
  // Social ad / pixel networks
  'connect.facebook.net', 'an.facebook.com', 'ads-twitter.com',
  'ads.linkedin.com', 'px.ads.linkedin.com', 'tr.snapchat.com',
  'ads.pinterest.com', 'ads.reddit.com', 'events.redditmedia.com',
  'ads.tiktok.com', 'analytics.tiktok.com',
  // Mobile-ish / misc ad SDKs
  'applovin.com', 'chartboost.com', 'unityads.unity3d.com', 'appodeal.com',
  'inmobi.com', 'mopub.com', 'startapp.com', 'vungle.com',
  'nativo.com', 'shareaholic.com', 'adrecover.com',
  'buysellads.com', 'carbonads.com', 'coinzilla.com',
  'adzerk.com', 'adbutler.com', 'revive-adserver.net',
  'adsoptimal.com', 'adf.ly', 'shorte.st'
];

const AD_PATH_PATTERNS = [
  /\/pagead\//i, /\/adsbygoogle/i, /\/adserver/i, /\/adframe/i,
  /\/adjs\.js/i, /\/ads\.js$/i, /\/ad\/?$/i, /\/advert/i,
  /\/prebid(\.js|-)/i, /\/bannerad/i, /\/popunder/i, /\/pop_?ad/i,
  /\/interstitial/i, /\/adx\.js/i, /\/dfp/i, /\/gpt\/pubads/i,
  /\/pubads\.g\.doubleclick/i, /\/tag\/js\/gpt/i, /\/banners?\.(js|gif|png|jpg)/i,
  /\/adserver\d*\//i, /\/ads\/.delivery/i, /\/showad/i, /\/getads?\.js/i
];

/** URL query parameters that exist only to track the clicker. */
const TRACK_PARAMS = [
  // Google Analytics / Ads
  'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content',
  'utm_id', 'utm_cid', 'utm_reader', 'utm_social', 'utm_name', 'utm_brand',
  'gclid', 'gclsrc', 'dclid', 'wbraid', 'gbraid', '_ga', '_gl',
  // Facebook / Instagram
  'fbclid', 'fb_action_ids', 'fb_action_types', 'fb_ref', 'fb_source',
  'igshid', 'igsh', 'si',
  // Microsoft / LinkedIn / X / TikTok / Pinterest / Reddit
  'msclkid', 'mc_cid', 'mc_eid', 'twclid', 'ttclid', 'trkid',
  'yclid', '_openstat', 'lipi', 'licu', 'trk', 'originalSubdomain',
  // Marketo / HubSpot / Mailchimp / Pardot / Veroot / misc email trackers
  'mkt_tok', 'hsCtaCampaign', 'hsCtaTracking', 'hsmi', 'hsenc', '__hssc',
  '__hstc', 'hsCteTracking', 'vero_id', 'vero_conv', 'wickedid',
  'oly_anonId', 'oly_enc_id', 'ck_subscriber_id', 's_cid', 'ss_email_id',
  // Matomo / Piwik / Plausible / misc analytics
  'pk_cid', 'pk_kwd', 'pk_campaign', 'mtm_cid', 'mtm_source', 'mtm_medium',
  'mtm_campaign', 'matomo_campaign', 'matomo_source', 'apcid',
  // Share / navigation crumbs
  'ref_src', 'ref_url', 'ref', 'spm', 'scm', 'share_id', 'shareId',
  'stm_', 'soc_src', 'soc_trk', 'sr_share', 'cmpid', 'otracker',
  'gid', 'cvid', 'ocid'
];

/** Cache of the firewall settings so request handling stays synchronous. */
let fwCache = Object.assign({}, DEFAULTS.firewall);
let modeCache = 'BASIC';

/** Is the network firewall enforcing for this mode right now?
 *  Ads are blocked in EVERY active mode (BASIC, PRO, MAXIMUM) - only
 *  OFF and an explicit "do not block" setting silence the firewall.
 *  'always' is accepted as a legacy alias of 'armed'. */
function firewallActive() {
  if (modeCache === 'OFF') return false;
  if (fwCache.adBlockMode === 'off') return false;
  return fwCache.adBlockMode === 'armed' || fwCache.adBlockMode === 'always';
}

function hostOfUrl(url) {
  try { return new URL(url).hostname.toLowerCase() || ''; }
  catch (e) { return ''; }
}

/** Registrable-domain guess (last two labels) - same rule content.js uses. */
function baseDomainOf(host) {
  const parts = (host || '').split('.').filter(Boolean);
  if (parts.length <= 2) return parts.join('.');
  return parts.slice(-2).join('.');
}

/** Does host sit on (or under) any known ad/tracker domain? */
function isAdHost(host) {
  if (!host) return false;
  for (const ad of AD_HOSTS) {
    if (!ad || ad.indexOf('.') === -1) continue; // skip guard entries
    if (host === ad || host.endsWith('.' + ad)) return true;
  }
  return false;
}

/** Remove tracking params from an http(s) URL. Returns null if clean. */
function stripTrackingParams(url) {
  try {
    const u = new URL(url);
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
    let changed = false;
    for (const name of Array.from(u.searchParams.keys())) {
      const lower = name.toLowerCase();
      const hit = TRACK_PARAMS.some((p) => {
        if (p.endsWith('_')) return lower.indexOf(p) === 0; // prefix family
        return lower === p;
      });
      if (hit) { u.searchParams.delete(name); changed = true; }
    }
    // reddit/twitter style fragment crumbs
    if (/(^|\/)#.*(utm_|fbclid|gclid)/i.test(u.href)) { /* rare - ignore */ }
    return changed ? u.href : null;
  } catch (e) {
    return null;
  }
}

/* ---------------------------------------------------------------------
 * 1. Install / update hook
 * ------------------------------------------------------------------- */

browser.runtime.onInstalled.addListener(async (details) => {
  const snapshot = await browser.storage.local.get('mode');
  if (!snapshot.mode) {
    await browser.storage.local.set(DEFAULTS);
  }
  // Keep the toolbar icon in sync with whatever mode is stored.
  const mode = snapshot.mode || 'BASIC';
  try {
    await browser.browserAction.setIcon({ path: iconPaths(mode) });
    await browser.browserAction.setBadgeBackgroundColor({
      color: MODE_BADGE_COLORS[mode] || MODE_BADGE_COLORS.BASIC
    });
    await browser.browserAction.setTitle({
      title: 'ScriptGuard - mode: ' + mode
    });
  } catch (e) { /* icon sync is cosmetic - never fatal */ }
  // Uncomment while debugging:
  // console.log('[ScriptGuard] onInstalled:', details.reason);
});

/* ---------------------------------------------------------------------
 * 2. Badge counting
 *
 * Every frame (top page and iframes) reports its own deleted-script
 * count. We keep the latest value per frame and display the sum, then
 * reset whenever the tab starts a new navigation.
 * ------------------------------------------------------------------- */

const badgeCounts = new Map(); // tabId -> Map(frameId -> count)

browser.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg && msg.type === 'sb:blockedCount' && sender.tab) {
    const tabId = sender.tab.id;
    const frameId = typeof sender.frameId === 'number' ? sender.frameId : 0;

    if (!badgeCounts.has(tabId)) {
      badgeCounts.set(tabId, new Map());
    }
    badgeCounts.get(tabId).set(frameId, Math.max(0, msg.count | 0));

    let total = 0;
    for (const n of badgeCounts.get(tabId).values()) {
      total += n;
    }
    setBadge(tabId, total);
    return;
  }

  if (msg && msg.type === 'sb:export') {
    exportRules();
    return;
  }

  if (msg && msg.type === 'sb:import' && msg.data) {
    importRules(msg.data);
    return;
  }

  if (msg && msg.type === 'sb:getNetStats') {
    const tabId = typeof msg.tabId === 'number' ? msg.tabId : null;
    const respond = async function () {
      let siteTotal = 0;
      try {
        const snapshot = await browser.storage.local.get('netStats');
        const stats = snapshot.netStats || {};
        const site = baseDomainOf(pageOriginHosts.get(tabId) || '');
        if (site) {
          for (const key of Object.keys(stats)) {
            if (key === site || site.endsWith('.' + key)) {
              siteTotal += stats[key] || 0;
              if (key === site) break;
            }
          }
        }
      } catch (e) { /* ignore */ }
      sendResponse({
        ok: true,
        tabBlocked: tabId !== null && netBlocked.get(tabId) || 0,
        siteBlocked: siteTotal,
        active: firewallActive()
      });
    };
    respond();
    return true; // async response
  }
});

function setBadge(tabId, count) {
  let text = '';
  if (count > 0) {
    text = count > 999 ? '999+' : String(count);
  }
  browser.browserAction.setBadgeText({ text: text, tabId: tabId });
  browser.browserAction.setBadgeBackgroundColor({
    color: MODE_BADGE_COLORS[modeCache] || MODE_BADGE_COLORS.BASIC,
    tabId: tabId
  });
}

/** Last http(s) origin seen per tab - used for stats keys and auto-wipe. */
const pageOriginHosts = new Map(); // tabId -> hostname
/** URLs we rewrote ourselves, so the strip loop never fights the browser. */
const rewrittenUrls = new Map();   // tabId -> last URL we set

browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status === 'loading') {
    badgeCounts.delete(tabId);
    netBlocked.delete(tabId);
    browser.browserAction.setBadgeText({ text: '', tabId: tabId });
  }
  // Remember the page host (for per-site firewall stats + auto-wipe) and
  // strip tracking parameters from navigations.
  const url = changeInfo.url || (tab && tab.url) || '';
  if (typeof url === 'string' && url) {
    const host = hostOfUrl(url);
    if (host) pageOriginHosts.set(tabId, host);
    if (fwCache.stripTracking && modeCache !== 'OFF' &&
        rewrittenUrls.get(tabId) !== url) {
      const cleaned = stripTrackingParams(url);
      if (cleaned && cleaned !== url) {
        rewrittenUrls.set(tabId, cleaned);
        browser.tabs.update(tabId, { url: cleaned, loadReplace: true })
          .catch(() => { /* tab navigated away - ignore */ });
      }
    }
  }
});

browser.tabs.onRemoved.addListener((tabId) => {
  badgeCounts.delete(tabId);
  netBlocked.delete(tabId);
  rewrittenUrls.delete(tabId);
  const host = pageOriginHosts.get(tabId);
  pageOriginHosts.delete(tabId);
  if (fwCache.autoWipe && host) {
    wipeSiteData(host);
  }
});

/* ---------------------------------------------------------------------
 * 3. Mode sync - icon colour, badge colour and toolbar tooltip
 * ------------------------------------------------------------------- */

browser.storage.onChanged.addListener((changes, area) => {
  if (area !== 'local') return;
  if (changes.mode) {
    const mode = changes.mode.newValue || 'BASIC';
    modeCache = mode;
    try {
      browser.browserAction.setIcon({ path: iconPaths(mode) });
      browser.browserAction.setTitle({ title: 'ScriptGuard - mode: ' + mode });
      browser.browserAction.setBadgeBackgroundColor({
        color: MODE_BADGE_COLORS[mode] || MODE_BADGE_COLORS.BASIC
      });
    } catch (e) { /* cosmetic - never fatal */ }
  }
  if (changes.firewall) {
    fwCache = Object.assign({}, DEFAULTS.firewall, changes.firewall.newValue || {});
  }
});

// Restore the mode-dependent icon on every browser start.
browser.storage.local.get(['mode', 'firewall']).then((res) => {
  modeCache = res.mode || 'BASIC';
  fwCache = Object.assign({}, DEFAULTS.firewall, res.firewall || {});
  try {
    browser.browserAction.setIcon({ path: iconPaths(modeCache) });
    browser.browserAction.setTitle({ title: 'ScriptGuard - mode: ' + modeCache });
  } catch (e) { /* ignore */ }
}).catch(() => { /* ignore */ });

/* ---------------------------------------------------------------------
 * 3b. Network firewall (ads, trackers, pings, GPC headers)
 *
 * Uses blocking webRequest (Firefox MV2) to cancel requests to known
 * ad / tracker infrastructure BEFORE anything is downloaded. This is
 * what actually removes ads: ad iframes, ad images, ad XHR and the
 * beacons that report your browsing.
 *
 *   - Host block: any request to a known ad/tracker domain.
 *   - Path block: generic ad paths, but ONLY on third-party requests.
 *   - Ping block: <a ping=...> hyperlink auditing is pure tracking.
 *   - Headers:    Sec-GPC + DNT appended to every outgoing request.
 *
 * Blocked counts are kept per tab (for the popup) and flushed to
 * storage.netStats every few seconds (all-time, per site).
 * ------------------------------------------------------------------- */

const netBlocked = new Map();  // tabId -> blocked count this page load
const netDelta = new Map();    // site key -> unflushed all-time delta
let netFlushTimer = null;

function bumpNetBlocked(tabId, siteKey) {
  if (tabId >= 0) netBlocked.set(tabId, (netBlocked.get(tabId) || 0) + 1);
  if (siteKey) netDelta.set(siteKey, (netDelta.get(siteKey) || 0) + 1);
  if (!netFlushTimer) netFlushTimer = setTimeout(flushNetStats, 3000);
}

async function flushNetStats() {
  netFlushTimer = null;
  if (netDelta.size === 0) return;
  const pending = Array.from(netDelta.entries());
  netDelta.clear();
  try {
    const snapshot = await browser.storage.local.get('netStats');
    const stats = snapshot.netStats || {};
    for (const [site, n] of pending) {
      stats[site] = (stats[site] || 0) + n;
    }
    await browser.storage.local.set({ netStats: stats });
  } catch (e) { /* stats are cosmetic - never fatal */ }
}

/** Third-party? The request target must not share the page's base domain. */
function isThirdPartyRequest(details) {
  const target = baseDomainOf(hostOfUrl(details.url));
  const origin = baseDomainOf(hostOfUrl(details.initiator || details.originUrl || ''));
  if (!origin || !target) return true; // no initiator = browser-level = treat strict
  return origin !== target;
}

browser.webRequest.onBeforeRequest.addListener((details) => {
  if (!firewallActive()) return;

  // Hyperlink auditing (<a ping>) is tracking, full stop.
  if (details.type === 'ping') {
    bumpNetBlocked(details.tabId, baseDomainOf(hostOfUrl(details.url)));
    return { cancel: true };
  }

  const host = hostOfUrl(details.url);
  if (isAdHost(host)) {
    bumpNetBlocked(details.tabId, baseDomainOf(host));
    return { cancel: true };
  }

  // Generic ad paths - only trusted on cross-site requests so a
  // first-party URL like /admin or /download can never false-positive.
  if (isThirdPartyRequest(details)) {
    const path = (() => {
      try { return new URL(details.url).pathname; } catch (e) { return ''; }
    })();
    for (const re of AD_PATH_PATTERNS) {
      if (re.test(path)) {
        bumpNetBlocked(details.tabId, baseDomainOf(host));
        return { cancel: true };
      }
    }
  }
}, { urls: ['<all_urls>'] }, ['blocking']);

/** Append Global Privacy Control + DNT to every outgoing request. */
browser.webRequest.onBeforeSendHeaders.addListener((details) => {
  if (!fwCache.gpc || modeCache === 'OFF') return;
  const headers = details.requestHeaders || [];
  const set = (name, value) => {
    for (const h of headers) {
      if (h.name.toLowerCase() === name.toLowerCase()) { h.value = value; return; }
    }
    headers.push({ name: name, value: value });
  };
  set('Sec-GPC', '1');
  set('DNT', '1');
  return { requestHeaders: headers };
}, { urls: ['<all_urls>'] }, ['blocking', 'requestHeaders']);

/** Wipe everything a site stored, called when its tab closes (opt-in). */
async function wipeSiteData(host) {
  try {
    const origin = 'https://' + host;
    await browser.browsingData.remove(
      { origins: [origin] },
      {
        cookies: true,
        localStorage: true,
        indexedDB: true,
        serviceWorkers: true,
        cacheStorage: true
      }
    );
    // http variant too, in case the site was served over plain http
    await browser.browsingData.remove(
      { origins: ['http://' + host] },
      { cookies: true, localStorage: true, indexedDB: true, serviceWorkers: true, cacheStorage: true }
    );
  } catch (e) { /* best effort - some data types may not exist */ }
}

/* ---------------------------------------------------------------------
 * 4. Export / import
 *
 * Export writes the whole settings object as pretty-printed JSON and
 * opens it in a new tab (blob URL), so the user can save it from there.
 * Import merges a JSON object into the existing database: per-domain
 * rule lists are unioned, never overwritten, so importing a friend's
 * rules cannot silently delete your own. Global whitelist and regex
 * lists are unioned as arrays; shields are merged key by key.
 * ------------------------------------------------------------------- */

async function exportRules() {
  try {
    const snapshot = await browser.storage.local.get(ALL_KEYS);
    const json = JSON.stringify(snapshot, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    await browser.tabs.create({ url: url });
    // Give the tab time to load before the blob is invalidated.
    setTimeout(() => URL.revokeObjectURL(url), 5 * 60 * 1000);
  } catch (err) {
    console.error('[ScriptGuard] export failed:', err);
  }
}

async function importRules(incoming) {
  try {
    const patch = {};

    if (incoming && typeof incoming.mode === 'string' && VALID_MODES.indexOf(incoming.mode) !== -1) {
      patch.mode = incoming.mode;
    }

    for (const key of ['rules', 'whitelist', 'labels', 'stats', 'heuristics']) {
      if (incoming && incoming[key] && typeof incoming[key] === 'object' && !Array.isArray(incoming[key])) {
        const current = await browser.storage.local.get(key);
        patch[key] = deepMergeMaps(current[key] || {}, incoming[key]);
      }
    }

    for (const key of ['globalWhitelist', 'regexRules']) {
      if (incoming && Array.isArray(incoming[key])) {
        const current = await browser.storage.local.get(key);
        patch[key] = union(current[key] || [], incoming[key].filter((h) => typeof h === 'string'));
      }
    }

    if (incoming && Array.isArray(incoming.trustedSites)) {
      const current = await browser.storage.local.get('trustedSites');
      patch.trustedSites = union(
        current.trustedSites || [],
        incoming.trustedSites.filter((h) => typeof h === 'string')
      );
    }

    if (incoming && incoming.shields && typeof incoming.shields === 'object' && !Array.isArray(incoming.shields)) {
      const current = await browser.storage.local.get('shields');
      const merged = Object.assign({ webrtc: true, blob: true }, current.shields || {});
      if (typeof incoming.shields.webrtc === 'boolean') merged.webrtc = incoming.shields.webrtc;
      if (typeof incoming.shields.blob === 'boolean') merged.blob = incoming.shields.blob;
      patch.shields = merged;
    }

    if (incoming && incoming.firewall && typeof incoming.firewall === 'object' && !Array.isArray(incoming.firewall)) {
      const current = await browser.storage.local.get('firewall');
      const merged = Object.assign({}, DEFAULTS.firewall, current.firewall || {});
      if (['off', 'armed', 'always'].indexOf(incoming.firewall.adBlockMode) !== -1) {
        merged.adBlockMode = incoming.firewall.adBlockMode;
      }
      if (typeof incoming.firewall.stripTracking === 'boolean') merged.stripTracking = incoming.firewall.stripTracking;
      if (typeof incoming.firewall.gpc === 'boolean') merged.gpc = incoming.firewall.gpc;
      if (typeof incoming.firewall.autoWipe === 'boolean') merged.autoWipe = incoming.firewall.autoWipe;
      patch.firewall = merged;
    }

    if (incoming && incoming.netStats && typeof incoming.netStats === 'object' && !Array.isArray(incoming.netStats)) {
      // All-time firewall counts: take the MAX of the two, never subtract.
      const current = await browser.storage.local.get('netStats');
      const merged = Object.assign({}, current.netStats || {});
      for (const site of Object.keys(incoming.netStats)) {
        const v = incoming.netStats[site] | 0;
        if (v > (merged[site] || 0)) merged[site] = v;
      }
      patch.netStats = merged;
    }

    if (Object.keys(patch).length > 0) {
      await browser.storage.local.set(patch);
    }
  } catch (err) {
    console.error('[ScriptGuard] import failed:', err);
  }
}

/** Merge two "domain -> array of strings" maps, unioning the arrays. */
function deepMergeMaps(target, source) {
  const out = Object.assign({}, target);
  for (const domain of Object.keys(source || {})) {
    const incomingList = Array.isArray(source[domain]) ? source[domain] : [];
    const existingList = Array.isArray(out[domain]) ? out[domain] : [];
    out[domain] = union(existingList, incomingList);
  }
  return out;
}

/** Union of two arrays of strings, order-preserving, no duplicates. */
function union(a, b) {
  const seen = new Set(a);
  const out = a.slice();
  for (const item of b) {
    if (!seen.has(item)) {
      seen.add(item);
      out.push(item);
    }
  }
  return out;
}
